### ISSUE TITLE
购物车问题

### ISSUE THREAD

**Issue by Lry0504** [liuyangjike/react-elm#1]
（1）购物车那里点击减，用户商品为0了再点击其他商品在购物车里面的价格也变化了，应该添加一个临界条件判断。
（2）清空购物车时，去结算应该变回还差20元起送
（3）profile页面中，当用户未登录时，头像应该显示为默认头像，initData那里应该在else里面添加newState.avatar = getImagePath(this.props.userInfo.avatar);然后img引入那里this.props.userInfo可以改为this.state
嘻嘻~项目写的很棒，拿来巩固react知识非常好用！！

**Comment by liuyangjike** [comment]
感谢🙏,已解决了
